from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine


MIGRATIONS = (
    "CREATE TABLE IF NOT EXISTS app_settings (id SERIAL PRIMARY KEY, key VARCHAR(128) UNIQUE NOT NULL, value TEXT NULL, updated_at TIMESTAMPTZ DEFAULT NOW())",
    "ALTER TABLE domains DROP CONSTRAINT IF EXISTS domains_domain_key",
    "DROP INDEX IF EXISTS ix_domains_domain",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS owner_id INTEGER NULL REFERENCES users(id) ON DELETE CASCADE",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS scheduler_mode VARCHAR(32) DEFAULT 'continuous'",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS pattern_slow_interval DOUBLE PRECISION DEFAULT 60.0",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS pattern_fast_interval DOUBLE PRECISION DEFAULT 0.5",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS pattern_window_start_minute INTEGER DEFAULT 31",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS pattern_window_end_minute INTEGER DEFAULT 34",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS confirmation_threshold INTEGER DEFAULT 3",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS available_recheck_enabled BOOLEAN DEFAULT false",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS available_recheck_interval DOUBLE PRECISION DEFAULT 1800.0",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS last_cycle_started_at TIMESTAMPTZ NULL",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS worker_heartbeat_at TIMESTAMPTZ NULL",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS last_success_at TIMESTAMPTZ NULL",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS available_at TIMESTAMPTZ NULL",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS last_seen_owner TEXT NULL",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS last_seen_rdap_status TEXT NULL",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS last_owner_change_at TIMESTAMPTZ NULL",
    "ALTER TABLE domains ADD COLUMN IF NOT EXISTS consecutive_failures INTEGER DEFAULT 0",
    "ALTER TABLE worker_nodes ADD COLUMN IF NOT EXISTS runtime_mode VARCHAR(32) DEFAULT 'unknown'",
    "ALTER TABLE worker_nodes ADD COLUMN IF NOT EXISTS registration_concurrency_multiplier DOUBLE PRECISION DEFAULT 2.0",
    "ALTER TABLE worker_nodes ADD COLUMN IF NOT EXISTS registration_max_concurrency INTEGER DEFAULT 64",
    "ALTER TABLE worker_nodes ADD COLUMN IF NOT EXISTS ssh_host VARCHAR(64) NULL",
    "ALTER TABLE worker_nodes ADD COLUMN IF NOT EXISTS ssh_port INTEGER DEFAULT 22",
    "ALTER TABLE worker_nodes ADD COLUMN IF NOT EXISTS ssh_username VARCHAR(64) NULL",
    "ALTER TABLE worker_nodes ADD COLUMN IF NOT EXISTS ssh_password TEXT NULL",
    "ALTER TABLE worker_nodes ADD COLUMN IF NOT EXISTS ssh_key_path VARCHAR(255) NULL",
    "ALTER TABLE worker_nodes ADD COLUMN IF NOT EXISTS ssh_last_check_status VARCHAR(32) NULL",
    "ALTER TABLE worker_nodes ADD COLUMN IF NOT EXISTS ssh_last_check_message TEXT NULL",
    "ALTER TABLE worker_nodes ADD COLUMN IF NOT EXISTS ssh_last_checked_at TIMESTAMPTZ NULL",
    "ALTER TABLE worker_tasks ADD COLUMN IF NOT EXISTS response_status_counts JSONB NULL",
    "ALTER TABLE worker_tasks ADD COLUMN IF NOT EXISTS response_error_counts JSONB NULL",
    "ALTER TABLE worker_tasks ADD COLUMN IF NOT EXISTS response_samples JSONB NULL",
    "ALTER TABLE attack_runs ADD COLUMN IF NOT EXISTS live_create_lease_worker_id INTEGER NULL",
    "ALTER TABLE attack_runs ADD COLUMN IF NOT EXISTS live_create_lease_task_id INTEGER NULL",
    "ALTER TABLE attack_runs ADD COLUMN IF NOT EXISTS live_create_lease_expires_at TIMESTAMPTZ NULL",
    "ALTER TABLE attack_runs ADD COLUMN IF NOT EXISTS live_create_accepted_worker_id INTEGER NULL",
    "ALTER TABLE attack_runs ADD COLUMN IF NOT EXISTS live_create_accepted_task_id INTEGER NULL",
    "ALTER TABLE attack_runs ADD COLUMN IF NOT EXISTS live_create_accepted_at TIMESTAMPTZ NULL",
    """
    CREATE TABLE IF NOT EXISTS worker_maintenance_jobs (
        id SERIAL PRIMARY KEY,
        worker_id INTEGER NOT NULL REFERENCES worker_nodes(id) ON DELETE CASCADE,
        action VARCHAR(32) NOT NULL,
        status VARCHAR(32) NOT NULL DEFAULT 'queued',
        log TEXT NULL,
        error_message TEXT NULL,
        started_at TIMESTAMPTZ NULL,
        finished_at TIMESTAMPTZ NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_worker_maintenance_jobs_worker_id ON worker_maintenance_jobs(worker_id)",
    "CREATE INDEX IF NOT EXISTS ix_worker_maintenance_jobs_status ON worker_maintenance_jobs(status)",
    "CREATE INDEX IF NOT EXISTS ix_worker_maintenance_jobs_action ON worker_maintenance_jobs(action)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_domains_owner_domain ON domains(owner_id, domain)",
    "ALTER TABLE proxies ADD COLUMN IF NOT EXISTS owner_id INTEGER NULL REFERENCES users(id) ON DELETE CASCADE",
    "ALTER TABLE logs ADD COLUMN IF NOT EXISTS owner_id INTEGER NULL REFERENCES users(id) ON DELETE CASCADE",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS max_domains INTEGER NULL",
    """
    CREATE TABLE IF NOT EXISTS zone_strategies (
        id SERIAL PRIMARY KEY,
        zone VARCHAR(32) NOT NULL,
        name VARCHAR(128) UNIQUE NOT NULL,
        timezone_name VARCHAR(64) NOT NULL DEFAULT 'UTC',
        rule_resolution_mode VARCHAR(32) NOT NULL DEFAULT 'priority',
        default_min_guaranteed_rps DOUBLE PRECISION NOT NULL DEFAULT 1.0,
        default_registrar_slug VARCHAR(64) NOT NULL DEFAULT 'gandi',
        is_active BOOLEAN NOT NULL DEFAULT true,
        notes TEXT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_zone_strategies_zone ON zone_strategies(zone)",
    "ALTER TABLE zone_strategies ADD COLUMN IF NOT EXISTS gandi_contact_extra_parameters TEXT NULL",
    "ALTER TABLE zone_strategies ADD COLUMN IF NOT EXISTS gandi_registration_extra_parameters TEXT NULL",
    """
    CREATE TABLE IF NOT EXISTS zone_rules (
        id SERIAL PRIMARY KEY,
        zone_strategy_id INTEGER NOT NULL REFERENCES zone_strategies(id) ON DELETE CASCADE,
        name VARCHAR(128) NOT NULL,
        is_enabled BOOLEAN NOT NULL DEFAULT true,
        priority INTEGER NOT NULL DEFAULT 100,
        schedule_type VARCHAR(32) NOT NULL DEFAULT 'hourly',
        hour INTEGER NULL,
        minute INTEGER NOT NULL DEFAULT 31,
        second INTEGER NOT NULL DEFAULT 30,
        weekdays VARCHAR(64) NULL,
        specific_date DATE NULL,
        window_duration_seconds INTEGER NOT NULL DEFAULT 95,
        execution_profile_mode VARCHAR(32) NOT NULL DEFAULT 'flat',
        notes TEXT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_zone_rules_zone_strategy_id ON zone_rules(zone_strategy_id)",
    "ALTER TABLE zone_rules ALTER COLUMN second SET DEFAULT 30",
    "ALTER TABLE zone_rules ALTER COLUMN window_duration_seconds SET DEFAULT 95",
    """
    CREATE TABLE IF NOT EXISTS zone_rule_phases (
        id SERIAL PRIMARY KEY,
        zone_rule_id INTEGER NOT NULL REFERENCES zone_rules(id) ON DELETE CASCADE,
        name VARCHAR(64) NOT NULL,
        sort_order INTEGER NOT NULL DEFAULT 0,
        start_offset_seconds INTEGER NOT NULL DEFAULT 0,
        duration_seconds INTEGER NOT NULL DEFAULT 0,
        rps_mode VARCHAR(32) NOT NULL DEFAULT 'percent',
        rps_value DOUBLE PRECISION NOT NULL DEFAULT 100.0,
        stop_on_success BOOLEAN NOT NULL DEFAULT true,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_zone_rule_phases_zone_rule_id ON zone_rule_phases(zone_rule_id)",
    """
    CREATE TABLE IF NOT EXISTS domain_rule_overrides (
        id SERIAL PRIMARY KEY,
        timezone_name VARCHAR(64) NOT NULL DEFAULT 'UTC',
        rule_resolution_mode VARCHAR(32) NOT NULL DEFAULT 'priority',
        default_min_guaranteed_rps DOUBLE PRECISION NOT NULL DEFAULT 1.0,
        notes TEXT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS domain_override_rules (
        id SERIAL PRIMARY KEY,
        domain_rule_override_id INTEGER NOT NULL REFERENCES domain_rule_overrides(id) ON DELETE CASCADE,
        name VARCHAR(128) NOT NULL,
        is_enabled BOOLEAN NOT NULL DEFAULT true,
        priority INTEGER NOT NULL DEFAULT 100,
        schedule_type VARCHAR(32) NOT NULL DEFAULT 'hourly',
        hour INTEGER NULL,
        minute INTEGER NOT NULL DEFAULT 31,
        second INTEGER NOT NULL DEFAULT 30,
        weekdays VARCHAR(64) NULL,
        specific_date DATE NULL,
        window_duration_seconds INTEGER NOT NULL DEFAULT 95,
        execution_profile_mode VARCHAR(32) NOT NULL DEFAULT 'flat',
        notes TEXT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_domain_override_rules_domain_rule_override_id ON domain_override_rules(domain_rule_override_id)",
    "ALTER TABLE domain_override_rules ALTER COLUMN second SET DEFAULT 30",
    "ALTER TABLE domain_override_rules ALTER COLUMN window_duration_seconds SET DEFAULT 95",
    """
    CREATE TABLE IF NOT EXISTS domain_override_phases (
        id SERIAL PRIMARY KEY,
        domain_override_rule_id INTEGER NOT NULL REFERENCES domain_override_rules(id) ON DELETE CASCADE,
        name VARCHAR(64) NOT NULL,
        sort_order INTEGER NOT NULL DEFAULT 0,
        start_offset_seconds INTEGER NOT NULL DEFAULT 0,
        duration_seconds INTEGER NOT NULL DEFAULT 0,
        rps_mode VARCHAR(32) NOT NULL DEFAULT 'percent',
        rps_value DOUBLE PRECISION NOT NULL DEFAULT 100.0,
        stop_on_success BOOLEAN NOT NULL DEFAULT true,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_domain_override_phases_domain_override_rule_id ON domain_override_phases(domain_override_rule_id)",
    "ALTER TABLE drop_domains ADD COLUMN IF NOT EXISTS zone_strategy_id INTEGER NULL REFERENCES zone_strategies(id) ON DELETE SET NULL",
    "ALTER TABLE drop_domains ADD COLUMN IF NOT EXISTS domain_rule_override_id INTEGER NULL REFERENCES domain_rule_overrides(id) ON DELETE SET NULL",
    "ALTER TABLE drop_domains ADD COLUMN IF NOT EXISTS strategy_mode VARCHAR(32) DEFAULT 'inherit_zone'",
    "ALTER TABLE drop_domains ADD COLUMN IF NOT EXISTS override_min_guaranteed_rps DOUBLE PRECISION NULL",
    "ALTER TABLE drop_domains ADD COLUMN IF NOT EXISTS readiness_reasons TEXT NULL",
    "ALTER TABLE drop_domains ADD COLUMN IF NOT EXISTS auto_start_enabled BOOLEAN NOT NULL DEFAULT false",
    "ALTER TABLE drop_domains ADD COLUMN IF NOT EXISTS auto_start_lead_seconds INTEGER NOT NULL DEFAULT 90",
    "ALTER TABLE drop_domains ALTER COLUMN window_start_second SET DEFAULT 30",
    "ALTER TABLE drop_domains ALTER COLUMN window_duration_seconds SET DEFAULT 95",
    "ALTER TABLE contact_profiles ADD COLUMN IF NOT EXISTS mobile VARCHAR(64) NULL",
    "ALTER TABLE contact_profiles ADD COLUMN IF NOT EXISTS fax VARCHAR(64) NULL",
    "ALTER TABLE contact_profiles ADD COLUMN IF NOT EXISTS lang VARCHAR(16) NULL",
    "ALTER TABLE contact_profiles ADD COLUMN IF NOT EXISTS data_obfuscated BOOLEAN NULL",
    "ALTER TABLE contact_profiles ADD COLUMN IF NOT EXISTS mail_obfuscated BOOLEAN NULL",
    "ALTER TABLE contact_profiles ADD COLUMN IF NOT EXISTS icann_contract_accept BOOLEAN NULL",
    "ALTER TABLE contact_profiles ADD COLUMN IF NOT EXISTS extra_parameters TEXT NULL",
    "ALTER TABLE registrar_accounts ADD COLUMN IF NOT EXISTS api_base_url VARCHAR(255) NULL",
    "ALTER TABLE drop_domains ADD COLUMN IF NOT EXISTS registration_extra_parameters TEXT NULL",
    "ALTER TABLE drop_domains ADD COLUMN IF NOT EXISTS dry_run_status VARCHAR(32) NULL",
    "ALTER TABLE drop_domains ADD COLUMN IF NOT EXISTS dry_run_http_status INTEGER NULL",
    "ALTER TABLE drop_domains ADD COLUMN IF NOT EXISTS dry_run_message TEXT NULL",
    """
    CREATE TABLE IF NOT EXISTS discovery_domains (
        id SERIAL PRIMARY KEY,
        fqdn VARCHAR(255) UNIQUE NOT NULL,
        zone VARCHAR(32) NOT NULL,
        status VARCHAR(32) NOT NULL DEFAULT 'tracking',
        is_enabled BOOLEAN NOT NULL DEFAULT true,
        check_interval_seconds INTEGER NOT NULL DEFAULT 10,
        source_mode VARCHAR(32) NOT NULL DEFAULT 'rdap',
        drop_prediction_enabled BOOLEAN NOT NULL DEFAULT true,
        last_lifecycle_stage VARCHAR(32) NULL,
        last_status_codes TEXT NULL,
        last_availability VARCHAR(32) NULL,
        last_checked_at TIMESTAMPTZ NULL,
        next_check_at TIMESTAMPTZ NULL,
        first_seen_redemption_at TIMESTAMPTZ NULL,
        last_seen_redemption_at TIMESTAMPTZ NULL,
        redemption_anchor_at TIMESTAMPTZ NULL,
        redemption_anchor_source VARCHAR(64) NULL,
        predicted_pending_delete_at TIMESTAMPTZ NULL,
        pending_delete_previous_seen_at TIMESTAMPTZ NULL,
        first_seen_pending_delete_at TIMESTAMPTZ NULL,
        last_seen_pending_delete_at TIMESTAMPTZ NULL,
        predicted_drop_start_at TIMESTAMPTZ NULL,
        predicted_drop_end_at TIMESTAMPTZ NULL,
        available_first_seen_at TIMESTAMPTZ NULL,
        last_error TEXT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_discovery_domains_fqdn ON discovery_domains(fqdn)",
    "CREATE INDEX IF NOT EXISTS ix_discovery_domains_zone ON discovery_domains(zone)",
    "CREATE INDEX IF NOT EXISTS ix_discovery_domains_status ON discovery_domains(status)",
    "CREATE INDEX IF NOT EXISTS ix_discovery_domains_next_check_at ON discovery_domains(next_check_at)",
    "ALTER TABLE discovery_domains ADD COLUMN IF NOT EXISTS redemption_anchor_at TIMESTAMPTZ NULL",
    "ALTER TABLE discovery_domains ADD COLUMN IF NOT EXISTS redemption_anchor_source VARCHAR(64) NULL",
    "ALTER TABLE discovery_domains ADD COLUMN IF NOT EXISTS predicted_pending_delete_at TIMESTAMPTZ NULL",
    "ALTER TABLE discovery_domains ADD COLUMN IF NOT EXISTS drop_prediction_enabled BOOLEAN NOT NULL DEFAULT true",
    "ALTER TABLE discovery_domains ALTER COLUMN check_interval_seconds SET DEFAULT 10",
    "UPDATE discovery_domains SET check_interval_seconds = 10 WHERE check_interval_seconds = 21600",
    "ALTER TABLE discovery_domains ADD COLUMN IF NOT EXISTS last_status_signature TEXT NULL",
    "ALTER TABLE discovery_domains ADD COLUMN IF NOT EXISTS last_owner_signature TEXT NULL",
    "ALTER TABLE discovery_domains ADD COLUMN IF NOT EXISTS last_change_at TIMESTAMPTZ NULL",
    "ALTER TABLE discovery_domains ADD COLUMN IF NOT EXISTS last_change_summary TEXT NULL",
    """
    INSERT INTO discovery_domains (
        fqdn,
        zone,
        status,
        is_enabled,
        check_interval_seconds,
        source_mode,
        drop_prediction_enabled,
        next_check_at,
        notes,
        created_at,
        updated_at
    )
    SELECT
        dd.fqdn,
        dd.zone,
        'tracking',
        true,
        10,
        'rdap',
        true,
        NOW(),
        'auto-created from existing drop domain',
        NOW(),
        NOW()
    FROM drop_domains dd
    WHERE NOT EXISTS (
        SELECT 1 FROM discovery_domains existing WHERE existing.fqdn = dd.fqdn
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS discovery_observations (
        id SERIAL PRIMARY KEY,
        discovery_domain_id INTEGER NOT NULL REFERENCES discovery_domains(id) ON DELETE CASCADE,
        source VARCHAR(32) NOT NULL,
        observed_at TIMESTAMPTZ DEFAULT NOW(),
        http_status INTEGER NULL,
        latency_ms INTEGER NULL,
        lifecycle_stage VARCHAR(32) NULL,
        availability_status VARCHAR(32) NULL,
        status_codes TEXT NULL,
        registrar_name TEXT NULL,
        owner_handle TEXT NULL,
        name_servers TEXT NULL,
        status_signature TEXT NULL,
        owner_signature TEXT NULL,
        change_detected BOOLEAN NOT NULL DEFAULT false,
        change_summary TEXT NULL,
        raw_response TEXT NULL,
        error TEXT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_discovery_observations_discovery_domain_id ON discovery_observations(discovery_domain_id)",
    "ALTER TABLE discovery_observations ADD COLUMN IF NOT EXISTS registrar_name TEXT NULL",
    "ALTER TABLE discovery_observations ADD COLUMN IF NOT EXISTS owner_handle TEXT NULL",
    "ALTER TABLE discovery_observations ADD COLUMN IF NOT EXISTS name_servers TEXT NULL",
    "ALTER TABLE discovery_observations ADD COLUMN IF NOT EXISTS status_signature TEXT NULL",
    "ALTER TABLE discovery_observations ADD COLUMN IF NOT EXISTS owner_signature TEXT NULL",
    "ALTER TABLE discovery_observations ADD COLUMN IF NOT EXISTS change_detected BOOLEAN NOT NULL DEFAULT false",
    "ALTER TABLE discovery_observations ADD COLUMN IF NOT EXISTS change_summary TEXT NULL",
    """
    CREATE TABLE IF NOT EXISTS discovery_worker_tasks (
        id SERIAL PRIMARY KEY,
        discovery_domain_id INTEGER NOT NULL REFERENCES discovery_domains(id) ON DELETE CASCADE,
        worker_id INTEGER NOT NULL REFERENCES worker_nodes(id) ON DELETE CASCADE,
        status VARCHAR(32) NOT NULL DEFAULT 'queued',
        source_mode VARCHAR(32) NOT NULL DEFAULT 'rdap',
        assigned_at TIMESTAMPTZ NULL,
        acknowledged_at TIMESTAMPTZ NULL,
        finished_at TIMESTAMPTZ NULL,
        error_message TEXT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_discovery_worker_tasks_discovery_domain_id ON discovery_worker_tasks(discovery_domain_id)",
    "CREATE INDEX IF NOT EXISTS ix_discovery_worker_tasks_worker_id ON discovery_worker_tasks(worker_id)",
    "CREATE INDEX IF NOT EXISTS ix_discovery_worker_tasks_status ON discovery_worker_tasks(status)",
    """
    CREATE TABLE IF NOT EXISTS zone_scan_jobs (
        id SERIAL PRIMARY KEY,
        zone VARCHAR(32) NOT NULL,
        source_type VARCHAR(32) NOT NULL DEFAULT 'zone_latest',
        source_date DATE NULL,
        status VARCHAR(32) NOT NULL DEFAULT 'queued',
        file_name VARCHAR(255) NULL,
        file_path TEXT NULL,
        download_url TEXT NULL,
        file_size_bytes INTEGER NULL,
        downloaded_bytes INTEGER NOT NULL DEFAULT 0,
        scanned_lines INTEGER NOT NULL DEFAULT 0,
        parsed_domains INTEGER NOT NULL DEFAULT 0,
        filtered_candidates INTEGER NOT NULL DEFAULT 0,
        submitted_rdap INTEGER NOT NULL DEFAULT 0,
        completed_rdap INTEGER NOT NULL DEFAULT 0,
        found_candidates INTEGER NOT NULL DEFAULT 0,
        error_count INTEGER NOT NULL DEFAULT 0,
        min_score INTEGER NOT NULL DEFAULT 35,
        limit_output INTEGER NOT NULL DEFAULT 20,
        max_rdap_checks INTEGER NOT NULL DEFAULT 300000,
        concurrency INTEGER NOT NULL DEFAULT 100,
        rdap_timeout_seconds DOUBLE PRECISION NOT NULL DEFAULT 5.0,
        pending_delete_min_days DOUBLE PRECISION NULL,
        pending_delete_max_days DOUBLE PRECISION NULL,
        reservoir_size INTEGER NOT NULL DEFAULT 300000,
        random_seed INTEGER NOT NULL DEFAULT 42,
        keep_file BOOLEAN NOT NULL DEFAULT true,
        started_at TIMESTAMPTZ NULL,
        finished_at TIMESTAMPTZ NULL,
        last_error TEXT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_zone_scan_jobs_zone ON zone_scan_jobs(zone)",
    "CREATE INDEX IF NOT EXISTS ix_zone_scan_jobs_status ON zone_scan_jobs(status)",
    """
    CREATE TABLE IF NOT EXISTS zone_scan_candidates (
        id SERIAL PRIMARY KEY,
        job_id INTEGER NOT NULL REFERENCES zone_scan_jobs(id) ON DELETE CASCADE,
        fqdn VARCHAR(255) NOT NULL,
        zone VARCHAR(32) NOT NULL,
        lifecycle_stage VARCHAR(32) NOT NULL,
        status_codes TEXT NULL,
        http_status INTEGER NULL,
        checked_at TIMESTAMPTZ NOT NULL,
        redemption_anchor_at TIMESTAMPTZ NULL,
        predicted_pending_delete_at TIMESTAMPTZ NULL,
        days_to_pending_delete DOUBLE PRECISION NULL,
        score INTEGER NOT NULL DEFAULT 0,
        reason TEXT NULL,
        error TEXT NULL,
        discovery_domain_id INTEGER NULL REFERENCES discovery_domains(id) ON DELETE SET NULL,
        is_ignored BOOLEAN NOT NULL DEFAULT false,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT uq_zone_scan_candidates_job_fqdn UNIQUE (job_id, fqdn)
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_zone_scan_candidates_job_id ON zone_scan_candidates(job_id)",
    "CREATE INDEX IF NOT EXISTS ix_zone_scan_candidates_fqdn ON zone_scan_candidates(fqdn)",
    "CREATE INDEX IF NOT EXISTS ix_zone_scan_candidates_zone ON zone_scan_candidates(zone)",
    "CREATE INDEX IF NOT EXISTS ix_zone_scan_candidates_lifecycle_stage ON zone_scan_candidates(lifecycle_stage)",
    "CREATE INDEX IF NOT EXISTS ix_zone_scan_candidates_discovery_domain_id ON zone_scan_candidates(discovery_domain_id)",
)


async def run_startup_migrations(engine: AsyncEngine) -> None:
    async with engine.begin() as conn:
        for statement in MIGRATIONS:
            await conn.execute(text(statement))
